### ISSUE TITLE
Crash (java.lang.NoClassDefFoundError: com/drppp/drtech/common/MetaTileEntities/muti/electric/standard/MetaTileEntityDeepGroundPump)

### ISSUE THREAD

**Issue by aking4125** [GTQT/DrTech#3]
Hello, upon adding this mod to my pack. The game crashes with the following report. Any ideas?

[crash-2024-10-16_10.45.20-client.txt](https://github.com/user-attachments/files/17397605/crash-2024-10-16_10.45.20-client.txt)
[debug.log](https://github.com/user-attachments/files/17397607/debug.log)

**Comment by Dr-ppp** [comment]
单独使用问题我这边不会处理  目前仅处理在GTQT环境下的问题
